use anyhow::{Context, Result};
use axum_server::tls_rustls::RustlsConfig;
use rcgen::{CertificateParams, KeyPair, SanType};
use std::net::IpAddr;
use std::path::{Path, PathBuf};
use x509_parser::prelude::*;

/// Default directory name for storing auto-generated certificates
const TLS_DIR_NAME: &str = "tls";
/// Default certificate file name
const CERT_FILENAME: &str = "cert.pem";
/// Default private key file name
const KEY_FILENAME: &str = "key.pem";
/// Version marker for auto-generated self-signed certificates
const CERT_VERSION_FILENAME: &str = "self_signed_version";
/// Current auto-generated certificate version (used to force regeneration on format changes)
const SELF_SIGNED_CERT_VERSION: u32 = 2;
/// Validity period for self-signed certificates (in days)
const SELF_SIGNED_VALIDITY_DAYS: u32 = 365;
/// Regenerate self-signed certificates this many days before they expire,
/// so clients never hit a hard expiry wall.
const RENEWAL_BUFFER_DAYS: u32 = 30;

/// TLS configuration for the gateway server.
#[derive(Clone, Debug)]
pub struct TlsConfig {
    /// Path to the TLS certificate file (PEM format)
    pub cert_path: Option<PathBuf>,
    /// Path to the TLS private key file (PEM format)
    pub key_path: Option<PathBuf>,
}

impl TlsConfig {
    /// Build an `axum_server::tls_rustls::RustlsConfig` from this TLS configuration.
    ///
    /// If `cert_path` and `key_path` are provided, loads certificates from those files.
    /// Otherwise, auto-generates a self-signed certificate (reusing a previously generated
    /// one if it exists in the default storage directory and has not expired).
    pub async fn build_rustls_config(&self) -> Result<RustlsConfig> {
        match (&self.cert_path, &self.key_path) {
            (Some(cert), Some(key)) => load_from_files(cert, key).await,
            (Some(_), None) => {
                anyhow::bail!(
                    "TLS certificate path provided without a key path. \
                     Please also set TLS_KEY."
                );
            }
            (None, Some(_)) => {
                anyhow::bail!(
                    "TLS key path provided without a certificate path. \
                     Please also set TLS_CERT."
                );
            }
            (None, None) => load_or_generate_self_signed().await,
        }
    }
}

/// Load TLS configuration from existing PEM files.
///
/// File-existence checks are intentionally omitted here because they are
/// already performed in `Config::validate()` at startup. Keeping a single
/// validation site avoids duplicate maintenance.
async fn load_from_files(cert_path: &Path, key_path: &Path) -> Result<RustlsConfig> {
    tracing::info!("Loading TLS certificate from: {}", cert_path.display());
    tracing::info!("Loading TLS private key from: {}", key_path.display());

    RustlsConfig::from_pem_file(cert_path, key_path)
        .await
        .context("Failed to load TLS certificate/key files. Ensure they are valid PEM format.")
}

/// Load a previously generated self-signed certificate, or generate a new one.
///
/// Certificates are regenerated when:
/// - No certificate files exist on disk yet.
/// - The existing certificate is expired or close to expiry (based on file mtime).
async fn load_or_generate_self_signed() -> Result<RustlsConfig> {
    let tls_dir = default_tls_dir()?;
    let cert_path = tls_dir.join(CERT_FILENAME);
    let key_path = tls_dir.join(KEY_FILENAME);

    // Reuse existing self-signed cert if both files are present and not expired
    if cert_path.exists() && key_path.exists() {
        if is_self_signed_cert_expired(&cert_path) {
            tracing::warn!(
                "Self-signed certificate in {} has expired or is close to expiry — regenerating.",
                tls_dir.display()
            );
        } else if is_self_signed_cert_compatible(&tls_dir) {
            tracing::info!(
                "Reusing existing self-signed certificate from: {}",
                tls_dir.display()
            );
            return RustlsConfig::from_pem_file(&cert_path, &key_path)
                .await
                .context(
                    "Failed to load previously generated self-signed certificate. \
                     Delete the files and restart to regenerate.",
                );
        } else {
            tracing::warn!(
                "Existing self-signed certificate is missing required SANs (likely generated by an older version) — regenerating."
            );
        }
    }

    // Generate a new self-signed certificate
    tracing::info!("No TLS certificate configured — generating a self-signed certificate...");

    let (cert_pem, key_pem) = generate_self_signed_cert()?;

    // Persist to disk so we can reuse on next startup
    create_tls_dir(&tls_dir)?;
    write_cert_file(&cert_path, &cert_pem)?;
    write_key_file(&key_path, &key_pem)?;
    write_cert_version_file(&tls_dir)?;

    tracing::info!("✅ Self-signed certificate saved to: {}", tls_dir.display());
    tracing::warn!(
        "⚠️  Self-signed certificates are not trusted by browsers/clients. \
         Use TLS_CERT and TLS_KEY to provide your own certificate for production use."
    );

    RustlsConfig::from_pem(cert_pem.into(), key_pem.into())
        .await
        .context("Failed to build RustlsConfig from generated self-signed certificate")
}

/// Generate a self-signed certificate and return (cert_pem, key_pem).
fn generate_self_signed_cert() -> Result<(String, String)> {
    let mut params = CertificateParams::default();

    // Set SANs with correct types — IP addresses must be SanType::IpAddress,
    // not DNS names, for clients to match them correctly.
    let mut sans = vec![
        SanType::DnsName(
            "localhost"
                .to_string()
                .try_into()
                .context("Failed to create DNS SAN for localhost")?,
        ),
        SanType::IpAddress(
            "127.0.0.1"
                .parse::<IpAddr>()
                .context("Failed to parse 127.0.0.1")?,
        ),
        SanType::IpAddress("::1".parse::<IpAddr>().context("Failed to parse ::1")?),
    ];

    if let Ok(hostname) = hostname::get() {
        if let Ok(hostname) = hostname.into_string() {
            let hostname = hostname.trim().to_string();
            if !hostname.is_empty() && hostname != "localhost" {
                match hostname.clone().try_into() {
                    Ok(dns_name) => {
                        tracing::info!("Added system hostname to certificate SANs: {}", hostname);
                        sans.push(SanType::DnsName(dns_name));
                    }
                    Err(_) => {
                        tracing::warn!("Skipping invalid hostname for TLS SAN: {}", hostname);
                    }
                }
            }
        }
    }

    params.subject_alt_names = sans;

    // Set validity period
    let now = ::time::OffsetDateTime::now_utc();
    params.not_before = now;
    params.not_after = now + ::time::Duration::days(SELF_SIGNED_VALIDITY_DAYS as i64);

    // Generate key pair and self-sign
    let key_pair = KeyPair::generate().context("Failed to generate TLS key pair")?;
    let cert = params
        .self_signed(&key_pair)
        .context("Failed to generate self-signed certificate")?;

    let cert_pem = cert.pem();
    let key_pem = key_pair.serialize_pem();

    tracing::info!(
        "Generated self-signed certificate (valid for {} days)",
        SELF_SIGNED_VALIDITY_DAYS
    );

    Ok((cert_pem, key_pem))
}

// ---------------------------------------------------------------------------
// Filesystem helpers
// ---------------------------------------------------------------------------

/// Create the TLS directory with restricted permissions.
fn create_tls_dir(tls_dir: &Path) -> Result<()> {
    std::fs::create_dir_all(tls_dir)
        .with_context(|| format!("Failed to create TLS directory: {}", tls_dir.display()))?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let perms = std::fs::Permissions::from_mode(0o700);
        if let Err(e) = std::fs::set_permissions(tls_dir, perms) {
            tracing::warn!(
                "Failed to restrict TLS directory permissions to 0700: {}. \
                 Other users may be able to list its contents.",
                e
            );
        }
    }

    Ok(())
}

/// Write the certificate PEM file (not sensitive — default permissions are fine).
fn write_cert_file(path: &Path, pem: &str) -> Result<()> {
    std::fs::write(path, pem)
        .with_context(|| format!("Failed to write certificate to: {}", path.display()))
}

/// Write the private key PEM file with restricted permissions (0600 on Unix).
///
/// On Unix the file is created with mode 0600 from the start to avoid a
/// TOCTOU window where the key is briefly world-readable.
fn write_key_file(path: &Path, pem: &str) -> Result<()> {
    #[cfg(unix)]
    {
        use std::io::Write;
        use std::os::unix::fs::OpenOptionsExt;

        let mut file = std::fs::OpenOptions::new()
            .write(true)
            .create(true)
            .truncate(true)
            .mode(0o600)
            .open(path)
            .with_context(|| format!("Failed to create private key file: {}", path.display()))?;

        file.write_all(pem.as_bytes())
            .with_context(|| format!("Failed to write private key to: {}", path.display()))?;

        // Explicitly set permissions to 0600 even if the file already existed
        // (mode(0o600) only applies when creating a new file)
        use std::os::unix::fs::PermissionsExt;
        let perms = std::fs::Permissions::from_mode(0o600);
        std::fs::set_permissions(path, perms).with_context(|| {
            format!(
                "Failed to set permissions on private key file: {}",
                path.display()
            )
        })?;

        Ok(())
    }

    #[cfg(not(unix))]
    {
        std::fs::write(path, pem)
            .with_context(|| format!("Failed to write private key to: {}", path.display()))?;

        tracing::warn!(
            "Non-Unix platform: could not restrict private key file permissions. \
             Please ensure {} is not readable by other users.",
            path.display()
        );

        Ok(())
    }
}

fn write_cert_version_file(tls_dir: &Path) -> Result<()> {
    let version_path = tls_dir.join(CERT_VERSION_FILENAME);
    std::fs::write(version_path, SELF_SIGNED_CERT_VERSION.to_string())
        .context("Failed to write self-signed certificate version file")
}

fn read_cert_version(tls_dir: &Path) -> Option<u32> {
    let version_path = tls_dir.join(CERT_VERSION_FILENAME);
    let version = std::fs::read_to_string(version_path).ok()?;
    version.trim().parse::<u32>().ok()
}

fn is_self_signed_cert_compatible(tls_dir: &Path) -> bool {
    matches!(read_cert_version(tls_dir), Some(version) if version >= SELF_SIGNED_CERT_VERSION)
}

/// Check whether a self-signed certificate is expired or close to expiry.
///
/// Parses the actual certificate file and checks its notAfter field.
/// Regeneration is triggered `RENEWAL_BUFFER_DAYS` before actual expiry
/// so clients never hit a hard failure.
fn is_self_signed_cert_expired(cert_path: &Path) -> bool {
    // Read the certificate file
    let cert_pem = match std::fs::read(cert_path) {
        Ok(pem) => pem,
        Err(e) => {
            tracing::debug!("Failed to read certificate file: {}", e);
            return false; // If file doesn't exist, not expired (will be generated)
        }
    };

    // Parse PEM and extract X.509 certificate
    let (_, pem_cert) = match parse_x509_pem(&cert_pem) {
        Ok(result) => result,
        Err(e) => {
            tracing::warn!("Failed to parse certificate PEM: {}", e);
            return true; // If we can't parse it, treat as expired to force regeneration
        }
    };

    // Parse the X.509 certificate from the PEM contents
    let (_, cert) = match parse_x509_certificate(&pem_cert.contents) {
        Ok(result) => result,
        Err(e) => {
            tracing::warn!("Failed to parse X.509 certificate: {}", e);
            return true; // Can't parse, treat as expired
        }
    };

    // Get the notAfter time
    let not_after = cert.validity().not_after;

    // Convert to Unix timestamp
    let not_after_timestamp = not_after.timestamp();

    // Calculate the renewal threshold (RENEWAL_BUFFER_DAYS before expiry)
    let renewal_buffer_secs = (RENEWAL_BUFFER_DAYS as i64) * 24 * 60 * 60;
    let renewal_threshold = not_after_timestamp - renewal_buffer_secs;

    // Get current time
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs() as i64;

    // Certificate should be renewed if we're past the renewal threshold
    let should_renew = now >= renewal_threshold;

    if should_renew {
        tracing::debug!(
            "Certificate expires at {} (Unix timestamp: {}), renewal threshold: {}, current time: {}",
            not_after,
            not_after_timestamp,
            renewal_threshold,
            now
        );
    }

    should_renew
}

/// Return the default directory for storing auto-generated TLS certificates.
///
/// Resolves to `~/.kiro-gateway/tls/`.
fn default_tls_dir() -> Result<PathBuf> {
    let home = dirs::home_dir().context(
        "Could not determine home directory. \
         Please provide TLS_CERT and TLS_KEY explicitly.",
    )?;
    Ok(home.join(".kiro-gateway").join(TLS_DIR_NAME))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_self_signed_cert() {
        let (cert_pem, key_pem) = generate_self_signed_cert().unwrap();

        assert!(cert_pem.starts_with("-----BEGIN CERTIFICATE-----"));
        assert!(cert_pem.contains("-----END CERTIFICATE-----"));
        assert!(key_pem.starts_with("-----BEGIN PRIVATE KEY-----"));
        assert!(key_pem.contains("-----END PRIVATE KEY-----"));
    }

    #[test]
    fn test_default_tls_dir() {
        let dir = match default_tls_dir() {
            Ok(dir) => dir,
            Err(err) => {
                eprintln!("Skipping test_default_tls_dir: default_tls_dir() failed: {err}");
                return;
            }
        };
        // Check path components instead of string suffix for cross-platform compatibility
        assert_eq!(dir.file_name().and_then(|s| s.to_str()), Some("tls"));
        assert_eq!(
            dir.parent()
                .and_then(|p| p.file_name())
                .and_then(|s| s.to_str()),
            Some(".kiro-gateway")
        );
    }

    #[test]
    fn test_tls_config_requires_both_cert_and_key() {
        // cert without key
        let config = TlsConfig {
            cert_path: Some(PathBuf::from("/tmp/cert.pem")),
            key_path: None,
        };
        let rt = tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .unwrap();
        let result = rt.block_on(config.build_rustls_config());
        assert!(result.is_err());
        assert!(result
            .unwrap_err()
            .to_string()
            .contains("without a key path"));

        // key without cert
        let config = TlsConfig {
            cert_path: None,
            key_path: Some(PathBuf::from("/tmp/key.pem")),
        };
        let result = rt.block_on(config.build_rustls_config());
        assert!(result.is_err());
        assert!(result
            .unwrap_err()
            .to_string()
            .contains("without a certificate path"));
    }

    #[test]
    fn test_is_self_signed_cert_expired_nonexistent_file() {
        // Non-existent file should not be considered expired
        let nonexistent_path = std::env::temp_dir().join("nonexistent_cert_12345.pem");
        assert!(!is_self_signed_cert_expired(&nonexistent_path));
    }

    #[test]
    fn test_is_self_signed_cert_expired_fresh_cert() {
        // Generate a fresh certificate and verify it's not expired
        let (cert_pem, _key_pem) = generate_self_signed_cert().unwrap();

        let dir = std::env::temp_dir().join(format!(
            "kiro_tls_test_fresh_{}_{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_nanos()
        ));
        std::fs::create_dir_all(&dir).unwrap();
        let cert_path = dir.join("test_cert.pem");
        std::fs::write(&cert_path, cert_pem).unwrap();

        // A freshly generated certificate should not be expired
        assert!(!is_self_signed_cert_expired(&cert_path));

        // Cleanup
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_is_self_signed_cert_expired_invalid_cert() {
        // Invalid certificate data should be treated as expired
        let dir = std::env::temp_dir().join(format!(
            "kiro_tls_test_invalid_{}_{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_nanos()
        ));
        std::fs::create_dir_all(&dir).unwrap();
        let cert_path = dir.join("test_cert.pem");
        std::fs::write(&cert_path, "invalid certificate data").unwrap();

        // Invalid certificate should be treated as expired (will be regenerated)
        assert!(is_self_signed_cert_expired(&cert_path));

        // Cleanup
        let _ = std::fs::remove_dir_all(&dir);
    }
}
